[package]
name = "jswt-ast"
version = "0.1.0"
authors = ["Nish Tahir <nishtahir@outlook.com>"]
edition = "2018"

[lib]
doctest = false

[dependencies]
jswt-common = {path = "../jswt-common"}
jswt-derive = {path = "../jswt-derive"}
jswt-types = {path = "../jswt-types"}